### ISSUE TITLE
Sinan dist issue on fresh install on OS X

### ISSUE THREAD

**Issue by paulj** [erlware-deprecated/sinan#79]
I've just downloaded a fresh copy of Sinan, generated an app with `sinan gen`, and then tried a `sinan dist`. I created two applications (ef_core and ef_web), and made no other structural changes. When I run `sinan dist`, I get the following error:

```
It looks like we couldn't satisfy all the dependency constraints We are going to search the space to see what the problem is but this could take a while
Unable to resolve compile time dependencies, probably do to the following constraints:
 constraint on proper with constraints [proper] originating from these application(s) ['__top_level__'] constraint on eunit with constraints [eunit] originating from these application(s) ['__top_level__']
```

**Comment by ericbmerritt** [comment]
Did you have the deps (https://github.com/downloads/erlware/sinan/deps.tar.gz) on your box? That is in your erlang path somewhere?

I realize this solution is non-optimal and I am working with a couple of the erlware folks to get this resolved by providing a manager.

Sinan needs those because of some brokenness with escript and how includes are made available and that there is no dependency download functionality available. The quick start runs through this. 

btw, I have done some work on the constraint solver and that particular error message should get a lot better soon.

**Comment by tsloughter** [comment]
Paul, checkout the newest release, 4.0.0, https://github.com/downloads/erlware/sinan/sinan

It should work without proper being installed.

**Comment by ericbmerritt** [comment]
and let us know if you run into issues.

**Comment by ericbmerritt** [comment]
This should be resolved now. Feel free to reopen if you continue to have trouble
